[kafkaHub.config]
# Flag to check whether to enable/disable security
SECURITY_ON = true

# Server ID is is used to uniquely identify each server
# Each server must have a unique ID
SERVER_ID = "server-1"

# IP and Port of the Kafka bootstrap node
KAFKA_BOOTSTRAP_NODE = "kafka.${kafka.profile}:${kafka.port}"

# Kafka topic which will get notified for websub topic registration/deregistration
# All the hubs must be pointed to the same Kafka topic to notify websub topic registration/deregistration
REGISTERED_WEBSUB_TOPICS_TOPIC = "registered-websub-topics"

# Kafka topic which stores consolidated websub topics for the hub
CONSOLIDATED_WEBSUB_TOPICS_TOPIC = "consolidated-websub-topics"

# Kafka topic which will get notified for websub subscription/unsubscription
# All the hubs must be pointed to the same Kafka topic to notify websub subscription/unsubscription
WEBSUB_SUBSCRIBERS_TOPIC = "registered-websub-subscribers"

# Kafka topic which is stores consolidated websub subscribers for this server
CONSOLIDATED_WEBSUB_SUBSCRIBERS_TOPIC = "consolidated-websub-subscribers"

# The interval in which Kafka consumers wait for new messages
POLLING_INTERVAL = 0.25

# The period in which Kafka close method waits to complete
GRACEFUL_CLOSE_PERIOD = 5.0

# The port that is used to start the hub
HUB_PORT = 9191

# The period between retry requests
MESSAGE_DELIVERY_RETRY_INTERVAL = 0.25

# The maximum retry count
MESSAGE_DELIVERY_COUNT = 2

# The message delivery timeout
MESSAGE_DELIVERY_TIMEOUT = 5.0

# The base URL of IDP
MOSIP_AUTH_BASE_URL = "${mosip.kernel.authmanager.url}/v1/authmanager"


# The token validation URL of IDP
MOSIP_AUTH_VALIDATE_TOKEN_URL = "/authorize/admin/validateToken"

# The token validation URL of IDP
DISK_SPACE_THRESHOLD = 10485760

# The token validation URL of IDP
PARTNER_USER_ID_PREFIX = "service-account-"


# The period between retry requests
INTENT_VERIFICATION_RETRY_INTERVAL = 0.2

# The maximum retry count
INTENT_VERIFICATION_COUNT = 2

# The period between retry requests
INTENT_VERIFICATION_BACKOFF_FACTOR = 1.5

# The maximum retry count
INTENT_VERIFICATION_MAX_INTERVAL = 2.0

# The maximum retry count
KAFKA_CONSUMER_MAX_POLL_RECORDS = 1000

# The maximum retry count
KAFKA_CONSUMER_FETCH_MAX_BYTES = 10485760

# The maximum retry count
KAFKA_CONSUMER_MAX_PARTITION_FETCH_BYTES = 4194304

# Kafka topic which is stores consolidated websub subscribers for this server
META_TOPICS = "registered-websub-topics,consolidated-websub-topics,registered-websub-subscribers,consolidated-websub-subscribers"

# consolidator base url
CONSOLIDATOR_BASE_URL = "${mosip.consolidator.url}"

# consolidator health endpoint
CONSOLIDATOR_HEALTH_ENDPOINT = "/consolidator/actuator/health"

#Encryption key that will be used to encrypt / decrypt the hub secret
HUB_SECRET_ENCRYPTION_KEY = "${hub.secret.encryption.key}"

# Below config will allow base64-encoded-bytes / alpha-numeric.
# Recommended to use base64-encoded-bytes since alpha-numeric is considered less secure. This is just given to ensure the backward compatiblity
HUB_SECRET_ENCRYPTION_KEY_FORMAT = "alpha-numeric"

# Optional (if supported by your Ballerina Kafka connector; set via env/props):
KAFKA_CONSUMER_FETCH_MIN_BYTES = 1048576     # 1 MiB – batch on broker
KAFKA_CONSUMER_FETCH_MAX_WAIT_MS = 25
KAFKA_CONSUMER_SESSION_TIMEOUT_MS = 15000
KAFKA_CONSUMER_HEARTBEAT_INTERVAL_MS = 3000
KAFKA_CONSUMER_PARTITION_ASSIGNMENT_STRATEGY = "cooperative-sticky"
# Producer-side (if hub produces events; otherwise set this where producers run):
KAFKA_PRODUCER_LINGER_MS = 10
KAFKA_PRODUCER_BATCH_SIZE = 131072           # 128 KiB
KAFKA_PRODUCER_COMPRESSION_TYPE = "snappy"   # or "lz4"

[ballerina.http.accessLogConfig]
# Enable printing access logs in console
console = true              # Default is false

[ballerina.http.traceLogAdvancedConfig]
# Enable printing trace logs in console
console = false              # Default is false

